spring:
  application:
    name: records-api
  datasource:
    url: jdbc:mysql://localhost:3306/records_db
    username: root
    password: rootadmin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: jdbc:mysql://localhost:3306/records_db
    user: root
    password: root
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000
